version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spa-app
    networks:
      - app-network
    expose:
      - 80
    environment:
      - NODE_ENV=production
    volumes:
      - ./build:/usr/share/nginx/html
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./build:/usr/share/nginx/html
    ports:
      - "80:80"
    restart: always

networks:
  app-network:
    driver: bridge
